SELECT * FROM exercise1.emp_1; CREATE DATABASE Exercise1;

#Question 1

CREATE TABLE EMP_1 (
EMP_NUM CHAR(3),
EMP_Lname VARCHAR(15),
EMP_FNAME VARCHAR(15),
EMP_INITIAL CHAR(1),
EMP_HIREDATE DATE,
JOB_CODE CHAR(3)
);

#Question 2

INSERT INTO EMP_1 (
EMP_NUM, EMP_Lname, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
VALUES
('226', 'Park', 'Chaeyoung', 'A', '1997-2-11', '016'),
('225', 'Arsolon', 'Raymond', 'S', '2002-9-25', '035');


INSERT INTO EMP_1 (
EMP_NUM, EMP_Lname, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
VALUES (
'229', 'Themove', 'Shane', 'T', '2006-07-04', '402');

SELECT * FROM EMP_1 WHERE JOB_CODE = '402';

SELECT * FROM EMP_1;